version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mivertowski"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
          - "System.*"
      testing:
        patterns:
          - "xunit*"
          - "Moq"
          - "FluentAssertions"
          - "coverlet*"
      build-tools:
        patterns:
          - "MinVer"
          - "DotNet.ReproducibleBuilds"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mivertowski"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"