using System;
using System.Runtime.InteropServices;

namespace DotCompute.Linq.Compilation;

/// <summary>
/// P/Invoke bindings for NVIDIA Runtime Compilation (NVRTC) library.
/// </summary>
/// <remarks>
/// NVRTC compiles CUDA C++ source code to PTX or CUBIN at runtime.
///
/// Key functions:
/// - nvrtcCreateProgram: Create compilation program from source
/// - nvrtcCompileProgram: Compile to PTX/CUBIN
/// - nvrtcGetPTX/nvrtcGetCUBIN: Get compiled output
/// - nvrtcGetProgramLog: Get compilation errors/warnings
///
/// Library names by platform:
/// - Linux: libnvrtc.so.12.0, libnvrtc.so (symlink)
/// - Windows: nvrtc64_120_0.dll
/// - macOS: Not supported (no NVIDIA GPUs on macOS)
/// </remarks>
internal static class NvrtcNative
{
    private const string NVRTC_LIBRARY = "nvrtc";

    #region NVRTC Result Codes

    /// <summary>
    /// NVRTC result codes.
    /// </summary>
    public enum nvrtcResult
    {
        NVRTC_SUCCESS = 0,
        NVRTC_ERROR_OUT_OF_MEMORY = 1,
        NVRTC_ERROR_PROGRAM_CREATION_FAILURE = 2,
        NVRTC_ERROR_INVALID_INPUT = 3,
        NVRTC_ERROR_INVALID_PROGRAM = 4,
        NVRTC_ERROR_INVALID_OPTION = 5,
        NVRTC_ERROR_COMPILATION = 6,
        NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = 7,
        NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = 8,
        NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = 9,
        NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = 10,
        NVRTC_ERROR_INTERNAL_ERROR = 11,
        NVRTC_ERROR_TIME_FILE_WRITE_FAILED = 12
    }

    #endregion

    #region NVRTC Program Management

    /// <summary>
    /// Creates an instance of nvrtcProgram with the given input parameters.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program (output).</param>
    /// <param name="src">CUDA program source code.</param>
    /// <param name="name">CUDA program name (for debugging).</param>
    /// <param name="numHeaders">Number of header files.</param>
    /// <param name="headers">Array of header source code strings.</param>
    /// <param name="includeNames">Array of header names.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcCreateProgram", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcCreateProgram(
        out IntPtr prog,
        [MarshalAs(UnmanagedType.LPStr)] string src,
        [MarshalAs(UnmanagedType.LPStr)] string? name,
        int numHeaders,
        IntPtr[]? headers,
        IntPtr[]? includeNames);

    /// <summary>
    /// Destroys the given program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcDestroyProgram", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcDestroyProgram(ref IntPtr prog);

    #endregion

    #region NVRTC Compilation

    /// <summary>
    /// Compiles the given program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="numOptions">Number of compiler options.</param>
    /// <param name="options">Array of compiler option strings.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcCompileProgram", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcCompileProgram(
        IntPtr prog,
        int numOptions,
        [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPStr)] string[]? options);

    #endregion

    #region NVRTC Output Retrieval

    /// <summary>
    /// Gets the size of the PTX generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="ptxSizeRet">Size of the generated PTX (including null terminator).</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetPTXSize", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetPTXSize(IntPtr prog, out IntPtr ptxSizeRet);

    /// <summary>
    /// Gets the PTX generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="ptx">Buffer to store the generated PTX.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetPTX", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetPTX(IntPtr prog, IntPtr ptx);

    /// <summary>
    /// Gets the size of the CUBIN generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="cubinSizeRet">Size of the generated CUBIN.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetCUBINSize", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetCUBINSize(IntPtr prog, out IntPtr cubinSizeRet);

    /// <summary>
    /// Gets the CUBIN generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="cubin">Buffer to store the generated CUBIN.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetCUBIN", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetCUBIN(IntPtr prog, IntPtr cubin);

    #endregion

    #region NVRTC Logs and Diagnostics

    /// <summary>
    /// Gets the size of the compilation log generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="logSizeRet">Size of the compilation log (including null terminator).</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetProgramLogSize", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetProgramLogSize(IntPtr prog, out IntPtr logSizeRet);

    /// <summary>
    /// Gets the compilation log generated by the program.
    /// </summary>
    /// <param name="prog">CUDA Runtime Compilation program.</param>
    /// <param name="log">Buffer to store the compilation log.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetProgramLog", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcGetProgramLog(IntPtr prog, IntPtr log);

    /// <summary>
    /// Gets the error string for a given NVRTC result code.
    /// </summary>
    /// <param name="result">NVRTC result code.</param>
    /// <returns>Error string describing the result.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcGetErrorString", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr nvrtcGetErrorString(nvrtcResult result);

    #endregion

    #region NVRTC Version Information

    /// <summary>
    /// Gets the NVRTC version.
    /// </summary>
    /// <param name="major">Major version number.</param>
    /// <param name="minor">Minor version number.</param>
    /// <returns>NVRTC result code.</returns>
    [DllImport(NVRTC_LIBRARY, EntryPoint = "nvrtcVersion", CallingConvention = CallingConvention.Cdecl)]
    public static extern nvrtcResult nvrtcVersion(out int major, out int minor);

    #endregion

    #region Helper Methods

    /// <summary>
    /// Converts NVRTC result to error string.
    /// </summary>
    public static string GetErrorString(nvrtcResult result)
    {
        IntPtr errorPtr = nvrtcGetErrorString(result);
        return Marshal.PtrToStringAnsi(errorPtr) ?? $"Unknown error: {result}";
    }

    /// <summary>
    /// Checks if NVRTC is available on this system.
    /// </summary>
    public static bool IsAvailable()
    {
        try
        {
            // Try to get version as a simple availability check
            nvrtcResult result = nvrtcVersion(out _, out _);
            return result == nvrtcResult.NVRTC_SUCCESS;
        }
        catch (DllNotFoundException)
        {
            return false;
        }
        catch (EntryPointNotFoundException)
        {
            return false;
        }
    }

    /// <summary>
    /// Gets the NVRTC version string.
    /// </summary>
    public static string GetVersion()
    {
        try
        {
            nvrtcResult result = nvrtcVersion(out int major, out int minor);
            if (result == nvrtcResult.NVRTC_SUCCESS)
            {
                return $"{major}.{minor}";
            }
            return "Unknown";
        }
        catch
        {
            return "Not Available";
        }
    }

    #endregion
}
