// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

namespace DotCompute.Core.Memory.P2P.Types;

/// <summary>
/// P2P optimization recommendations for improving system performance.
/// </summary>
/// <remarks>
/// <para>
/// Generated by <see cref="P2POptimizer"/> based on analysis of transfer history,
/// performance patterns, and topology characteristics.
/// </para>
/// <para>
/// Recommendations are categorized into performance (device-pair specific),
/// topology (system-wide), and configuration (settings tuning).
/// </para>
/// </remarks>
public sealed class P2POptimizationRecommendations
{
    /// <summary>
    /// Gets or sets when these recommendations were generated.
    /// </summary>
    public required DateTimeOffset GeneratedAt { get; init; }

    /// <summary>
    /// Gets or sets device-pair specific performance recommendations.
    /// </summary>
    public required IList<P2PPerformanceRecommendation> PerformanceRecommendations { get; init; }

    /// <summary>
    /// Gets or sets system-wide topology recommendations.
    /// </summary>
    public required IList<P2PTopologyRecommendation> TopologyRecommendations { get; init; }

    /// <summary>
    /// Gets or sets configuration parameter recommendations.
    /// </summary>
    public required IList<P2PConfigurationRecommendation> ConfigurationRecommendations { get; init; }
}

/// <summary>
/// Performance recommendation for specific device pairs.
/// </summary>
/// <remarks>
/// Identifies underperforming device pairs and suggests alternative strategies
/// with estimated improvement potential.
/// </remarks>
public sealed class P2PPerformanceRecommendation
{
    /// <summary>
    /// Gets or sets the device pair identifier (format: "sourceId -&gt; targetId").
    /// </summary>
    public required string DevicePair { get; init; }

    /// <summary>
    /// Gets or sets the current efficiency score (0.0-1.0).
    /// </summary>
    public required double CurrentEfficiency { get; init; }

    /// <summary>
    /// Gets or sets the recommended transfer strategy.
    /// </summary>
    public required P2PTransferStrategy RecommendedStrategy { get; init; }

    /// <summary>
    /// Gets or sets the expected performance improvement (0.0-1.0).
    /// </summary>
    /// <remarks>
    /// Estimated throughput gain if recommendation is applied.
    /// </remarks>
    public required double ExpectedImprovement { get; init; }

    /// <summary>
    /// Gets or sets the priority level (High, Medium, Low).
    /// </summary>
    public required string Priority { get; init; }
}

/// <summary>
/// Topology recommendation for overall system optimization.
/// </summary>
/// <remarks>
/// Identifies opportunities to improve the overall P2P topology configuration,
/// such as underutilized high-performance links or suboptimal routing.
/// </remarks>
public sealed class P2PTopologyRecommendation
{
    /// <summary>
    /// Gets or sets the type of topology recommendation.
    /// </summary>
    /// <remarks>
    /// Examples: "UnderutilizedHighPerformancePath", "SuboptimalRouting", "BottleneckDetected".
    /// </remarks>
    public required string RecommendationType { get; init; }

    /// <summary>
    /// Gets or sets the affected device pair.
    /// </summary>
    public required string DevicePair { get; init; }

    /// <summary>
    /// Gets or sets a human-readable description of the recommendation.
    /// </summary>
    public required string Description { get; init; }

    /// <summary>
    /// Gets or sets the expected impact (High, Medium, Low).
    /// </summary>
    public required string Impact { get; init; }
}

/// <summary>
/// Configuration recommendation for system settings.
/// </summary>
/// <remarks>
/// Suggests changes to global P2P configuration parameters based on
/// observed workload patterns and performance characteristics.
/// </remarks>
public sealed class P2PConfigurationRecommendation
{
    /// <summary>
    /// Gets or sets the configuration category.
    /// </summary>
    /// <remarks>
    /// Examples: "GlobalOptimization", "MemoryManagement", "SchedulingPolicy".
    /// </remarks>
    public required string Category { get; init; }

    /// <summary>
    /// Gets or sets the setting name.
    /// </summary>
    public required string Setting { get; init; }

    /// <summary>
    /// Gets or sets the recommended value.
    /// </summary>
    public required string RecommendedValue { get; init; }

    /// <summary>
    /// Gets or sets the reason for this recommendation.
    /// </summary>
    public required string Reason { get; init; }

    /// <summary>
    /// Gets or sets the expected benefit.
    /// </summary>
    /// <remarks>
    /// Qualitative or quantitative description of performance gain.
    /// </remarks>
    public required string ExpectedBenefit { get; init; }
}

/// <summary>
/// P2P optimization statistics.
/// </summary>
/// <remarks>
/// <para>
/// Tracks cumulative metrics for all optimization operations performed by
/// the <see cref="P2POptimizer"/>.
/// </para>
/// <para>
/// Useful for monitoring optimization effectiveness and capacity planning.
/// </para>
/// </remarks>
public sealed class P2POptimizationStatistics
{
    /// <summary>
    /// Gets or sets the total number of optimized transfers.
    /// </summary>
    public long TotalOptimizedTransfers { get; set; }

    /// <summary>
    /// Gets or sets the number of active optimization profiles.
    /// </summary>
    /// <remarks>
    /// One profile per unique device pair.
    /// </remarks>
    public int OptimizationProfilesActive { get; set; }

    /// <summary>
    /// Gets or sets the average optimization score across all profiles (0.0-1.0).
    /// </summary>
    public double AverageOptimizationScore { get; set; }

    /// <summary>
    /// Gets or sets the average efficiency score across all profiles (0.0-1.0).
    /// </summary>
    public double AverageEfficiencyScore { get; set; }

    /// <summary>
    /// Gets or sets the total number of transfers in history.
    /// </summary>
    public long TotalTransferHistory { get; set; }

    /// <summary>
    /// Gets or sets the number of adaptive optimizations applied.
    /// </summary>
    /// <remarks>
    /// Count of automatic parameter adjustments based on performance feedback.
    /// </remarks>
    public long AdaptiveOptimizationsApplied { get; set; }

    /// <summary>
    /// Gets or sets when the last optimization was performed.
    /// </summary>
    public DateTimeOffset LastOptimizationTime { get; set; }
}
