#!/bin/bash
# Fix CA1032: Add standard exception constructors

set -e

echo "=========================================="
echo "Fixing CA1032: Exception Constructors"
echo "=========================================="

TARGET_DIR="src"
OUTPUT_FILE="docs/exception-constructors-todo.md"

echo "Scanning for custom exceptions..."

cat > "$OUTPUT_FILE" << 'HEADER'
# Custom Exceptions Requiring Standard Constructors

Generated by: scripts/fix-automation/05-add-exception-constructors.sh

## Instructions

For each exception below, add these three constructors:

```csharp
public class YourException : Exception
{
    // Add these three:
    public YourException() { }

    public YourException(string message) : base(message) { }

    public YourException(string message, Exception innerException)
        : base(message, innerException) { }

    // Keep your existing custom constructors below...
}
```

## Exceptions to Fix

HEADER

# Find exception classes without standard constructors
find "$TARGET_DIR" -name "*.cs" -type f | while read -r file; do
    grep -n "class.*Exception.*:" "$file" | while read -r line; do
        line_num=$(echo "$line" | cut -d: -f1)
        class_name=$(echo "$line" | sed 's/.*class \(\w*Exception\).*/\1/')

        # Check if file has all three standard constructors for this exception
        has_default=$(grep -A 50 "class $class_name" "$file" | grep -c "public $class_name()" || true)
        has_message=$(grep -A 50 "class $class_name" "$file" | grep -c "public $class_name(string message)" || true)
        has_inner=$(grep -A 50 "class $class_name" "$file" | grep -c "Exception innerException" || true)

        if [ "$has_default" -eq 0 ] || [ "$has_message" -eq 0 ] || [ "$has_inner" -eq 0 ]; then
            echo "### $class_name" >> "$OUTPUT_FILE"
            echo "**File**: $file:$line_num" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "Missing constructors:" >> "$OUTPUT_FILE"
            [ "$has_default" -eq 0 ] && echo "- [ ] Default constructor" >> "$OUTPUT_FILE"
            [ "$has_message" -eq 0 ] && echo "- [ ] Message constructor" >> "$OUTPUT_FILE"
            [ "$has_inner" -eq 0 ] && echo "- [ ] Inner exception constructor" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        fi
    done
done

echo ""
echo "=========================================="
echo "Analysis Complete!"
echo "=========================================="
echo ""
echo "Report generated: $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "1. Review the report"
echo "2. Use IDE snippet 'exctors' for each exception"
echo "3. Build and verify: dotnet build 2>&1 | grep CA1032"
echo ""
echo "Estimated time: 4-6 hours for 491 exceptions"
