// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

namespace DotCompute.Abstractions.Messaging;

/// <summary>
/// Base interface for type-safe messages exchanged between Ring Kernels.
/// </summary>
/// <remarks>
/// Ring Kernel messages provide type-safe communication between GPU-resident
/// actors in the Orleans.GpuBridge.Core integration. Messages support:
/// - Unique identification for tracking and deduplication
/// - Priority-based processing
/// - Correlation for request/response patterns
/// - Zero-copy serialization using spans
///
/// <para>
/// Implementations should be generated using the [GenerateMessageSerializer] attribute
/// to ensure optimal serialization performance.
/// </para>
///
/// <para>
/// <b>Example:</b>
/// <code>
/// [GenerateMessageSerializer]
/// public partial class ComputeRequest : IRingKernelMessage
/// {
///     public Guid MessageId { get; set; } = Guid.NewGuid();
///     public string MessageType => "ComputeRequest";
///     public byte Priority { get; set; } = 128;
///     public Guid? CorrelationId { get; set; }
///
///     // Application data
///     public int InputValue { get; set; }
///     public float[] Data { get; set; } = Array.Empty&lt;float&gt;();
///
///     // Serialization auto-generated by source generator
/// }
/// </code>
/// </para>
/// </remarks>
public interface IRingKernelMessage
{
    /// <summary>
    /// Gets or sets the unique message identifier.
    /// </summary>
    /// <remarks>
    /// Used for message tracking, logging, and deduplication.
    /// Should be unique across all messages in the system.
    /// Default: <see cref="Guid.NewGuid()"/>
    /// </remarks>
    public Guid MessageId { get; set; }

    /// <summary>
    /// Gets the message type identifier for deserialization.
    /// </summary>
    /// <remarks>
    /// Used by the runtime to determine which concrete type to instantiate
    /// during deserialization. Must be consistent across all instances of
    /// the same message type.
    ///
    /// Typically returns the type name (e.g., "ComputeRequest").
    /// </remarks>
    public string MessageType { get; }

    /// <summary>
    /// Gets or sets the message priority (0-255).
    /// </summary>
    /// <remarks>
    /// Higher values indicate higher priority. Used by priority queues
    /// to determine processing order.
    /// - 0-63: Low priority (batch processing)
    /// - 64-127: Normal priority (default)
    /// - 128-191: High priority (interactive)
    /// - 192-255: Critical priority (system messages)
    ///
    /// Default: 128 (normal priority)
    /// </remarks>
    public byte Priority { get; set; }

    /// <summary>
    /// Gets or sets the optional correlation identifier for request/response patterns.
    /// </summary>
    /// <remarks>
    /// Used to correlate responses with their originating requests.
    /// Set to the <see cref="MessageId"/> of the request message when
    /// sending a response.
    ///
    /// Null for standalone messages that don't require correlation.
    /// </remarks>
    public Guid? CorrelationId { get; set; }

    /// <summary>
    /// Gets the message payload size in bytes.
    /// </summary>
    /// <remarks>
    /// Returns the total size of the serialized message including:
    /// - MessageId (16 bytes)
    /// - Priority (1 byte)
    /// - CorrelationId (16 bytes if present, 1 byte null marker otherwise)
    /// - Application data (variable)
    ///
    /// Used for memory allocation and capacity planning.
    /// Source generator calculates this automatically.
    /// </remarks>
    public int PayloadSize { get; }

    /// <summary>
    /// Serializes the message to a byte span.
    /// </summary>
    /// <returns>A read-only span containing the serialized message bytes.</returns>
    /// <remarks>
    /// Uses <see cref="System.Buffers.Binary.BinaryPrimitives"/> for efficient
    /// serialization with explicit endianness (little-endian).
    ///
    /// The returned span is valid only until the next call to Serialize().
    /// Callers should copy the data if longer retention is needed.
    ///
    /// Auto-generated by source generator for optimal performance.
    /// </remarks>
    public ReadOnlySpan<byte> Serialize();

    /// <summary>
    /// Deserializes the message from a byte span.
    /// </summary>
    /// <param name="data">The serialized message bytes.</param>
    /// <remarks>
    /// Reads data using <see cref="System.Buffers.Binary.BinaryPrimitives"/>
    /// with explicit endianness (little-endian).
    ///
    /// The data span must be at least <see cref="PayloadSize"/> bytes.
    ///
    /// Auto-generated by source generator for optimal performance.
    /// </remarks>
    public void Deserialize(ReadOnlySpan<byte> data);
}
