// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Text;
using Microsoft.CodeAnalysis;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates unified wrapper classes for kernel methods.
/// </summary>
public sealed class KernelWrapperEmitter
{
    /// <summary>
    /// Generates a unified wrapper class for cross-backend execution.
    /// </summary>
    /// <param name="method">The kernel method to generate a wrapper for.</param>
    /// <param name="compilation">The compilation context.</param>
    /// <returns>The generated wrapper source code.</returns>
    public static string GenerateUnifiedWrapper(KernelMethodInfo method, Compilation compilation)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine("using System.Threading.Tasks;");
        _ = source.AppendLine();

        var namespaceName = $"{method.Namespace}.Generated";
        _ = source.AppendLine($"namespace {namespaceName}");
        _ = source.AppendLine("{");
        _ = source.AppendLine($"    public static class {method.Name}Wrapper");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        // Wrapper implementation placeholder");
        _ = source.AppendLine("    }");
        _ = source.AppendLine("}");

        return source.ToString();
    }

    /// <summary>
    /// Generates a kernel invoker class for dynamic execution.
    /// </summary>
    /// <param name="kernelClass">The kernel class to generate an invoker for.</param>
    /// <param name="allMethods">All kernel methods for lookup.</param>
    /// <returns>The generated invoker source code.</returns>
    public static string GenerateKernelInvoker(KernelClassInfo kernelClass, IReadOnlyList<KernelMethodInfo> allMethods)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine();

        var namespaceName = $"{kernelClass.Namespace}.Generated";
        _ = source.AppendLine($"namespace {namespaceName}");
        _ = source.AppendLine("{");
        _ = source.AppendLine($"    public static class {kernelClass.Name}Invoker");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        // Invoker implementation placeholder");
        _ = source.AppendLine("    }");
        _ = source.AppendLine("}");

        return source.ToString();
    }
}