// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Text;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates kernel registry code for runtime discovery.
/// </summary>
public sealed class KernelRegistrationEmitter
{
    /// <summary>
    /// Generates the kernel registry containing all kernel metadata.
    /// </summary>
    /// <param name="kernelMethods">The kernel methods to include in the registry.</param>
    /// <param name="kernelClasses">The kernel classes to include in the registry.</param>
    /// <returns>The generated registry source code.</returns>
    public static string GenerateKernelRegistry(IReadOnlyList<KernelMethodInfo> kernelMethods, IReadOnlyList<KernelClassInfo> kernelClasses)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine("using System.Collections.Generic;");
        _ = source.AppendLine();

        _ = source.AppendLine("namespace DotCompute.Generated");
        _ = source.AppendLine("{");
        _ = source.AppendLine("    public static class KernelRegistry");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        // Registry implementation placeholder");
        _ = source.AppendLine("    }");
        _ = source.AppendLine("}");

        return source.ToString();
    }
}