// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Collections.Generic;
using System.Text;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates kernel registry code for runtime discovery.
/// </summary>
public sealed class KernelRegistrationEmitter
{
    /// <summary>
    /// Generates the kernel registry containing all kernel metadata.
    /// </summary>
    /// <param name="kernelMethods">The kernel methods to include in the registry.</param>
    /// <param name="kernelClasses">The kernel classes to include in the registry.</param>
    /// <returns>The generated registry source code.</returns>
    public static string GenerateKernelRegistry(List<KernelMethodInfo> kernelMethods, List<KernelClassInfo> kernelClasses)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine();

        source.AppendLine("namespace DotCompute.Generated");
        source.AppendLine("{");
        source.AppendLine("    public static class KernelRegistry");
        source.AppendLine("    {");
        source.AppendLine("        // Registry implementation placeholder");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }
}