// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Text;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates kernel metadata for runtime introspection.
/// </summary>
public sealed class KernelMetadataEmitter
{
    /// <summary>
    /// Generates kernel metadata source code.
    /// </summary>
    /// <param name="kernelMethods">The kernel methods to include in metadata.</param>
    /// <returns>The generated metadata source code.</returns>
    public static string GenerateKernelMetadata(IReadOnlyList<KernelMethodInfo> kernelMethods)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine("using System.Collections.Generic;");
        _ = source.AppendLine();

        _ = source.AppendLine("namespace DotCompute.Generated");
        _ = source.AppendLine("{");
        _ = source.AppendLine("    public static class KernelMetadata");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        // Metadata implementation placeholder");
        _ = source.AppendLine("    }");
        _ = source.AppendLine("}");

        return source.ToString();
    }
}
