// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Text;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates kernel registry code for runtime discovery.
/// </summary>
public sealed class KernelRegistrationEmitter
{
    /// <summary>
    /// Generates the kernel registry containing all kernel metadata.
    /// </summary>
    /// <param name="kernelMethods">The kernel methods to include in the registry.</param>
    /// <param name="kernelClasses">The kernel classes to include in the registry.</param>
    /// <returns>The generated registry source code.</returns>
    /// <remarks>
    /// The registry provides runtime access to all kernels via:
    /// - AddKernel: Registers kernel metadata
    /// - GetAvailableKernels: Returns list of all registered kernels
    /// - GetKernelInfo: Retrieves metadata for a specific kernel
    /// </remarks>
    public static string GenerateKernelRegistry(IReadOnlyList<KernelMethodInfo> kernelMethods, IReadOnlyList<KernelClassInfo> kernelClasses)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("#nullable enable");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine("using System.Collections.Generic;");
        _ = source.AppendLine("using System.Linq;");
        _ = source.AppendLine();

        _ = source.AppendLine("namespace DotCompute.Generated");
        _ = source.AppendLine("{");
        _ = source.AppendLine("    /// <summary>");
        _ = source.AppendLine("    /// Registry of all generated kernels for runtime discovery.");
        _ = source.AppendLine("    /// </summary>");
        _ = source.AppendLine("    public static class KernelRegistry");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        private static readonly Dictionary<string, KernelMetadata> _kernels = new()");
        _ = source.AppendLine("        {");

        // Generate kernel registrations
        foreach (var method in kernelMethods)
        {
            var fullName = $"{method.ContainingType}.{method.Name}";
            _ = source.AppendLine($"            {{ \"{fullName}\", new KernelMetadata");
            _ = source.AppendLine("            {");
            _ = source.AppendLine($"                Name = \"{method.Name}\",");
            _ = source.AppendLine($"                FullyQualifiedName = \"{fullName}\",");
            _ = source.AppendLine($"                ContainingType = \"{method.ContainingType}\",");
            _ = source.AppendLine($"                Namespace = \"{method.Namespace}\",");
            _ = source.AppendLine($"                Backends = new[] {{ {string.Join(", ", method.Backends.Select(b => $"\"{b}\""))} }},");
            _ = source.AppendLine($"                VectorSize = {method.VectorSize},");
            _ = source.AppendLine($"                IsParallel = {(method.IsParallel ? "true" : "false")},");
            _ = source.AppendLine($"                ParameterCount = {method.Parameters.Count}");
            _ = source.AppendLine("            }},");
        }

        _ = source.AppendLine("        };");
        _ = source.AppendLine();

        // Generate AddKernel method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Adds a kernel to the registry.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static void AddKernel(string name, KernelMetadata metadata)");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            _kernels[name] = metadata;");
        _ = source.AppendLine("        }");
        _ = source.AppendLine();

        // Generate GetAvailableKernels method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Gets a list of all available kernel names.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static IReadOnlyList<string> GetAvailableKernels()");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            return _kernels.Keys.ToList();");
        _ = source.AppendLine("        }");
        _ = source.AppendLine();

        // Generate GetKernelInfo method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Gets metadata for a specific kernel.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static KernelMetadata? GetKernelInfo(string name)");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            return _kernels.TryGetValue(name, out var metadata) ? metadata : null;");
        _ = source.AppendLine("        }");
        _ = source.AppendLine("    }");
        _ = source.AppendLine();

        // Generate KernelMetadata class
        _ = source.AppendLine("    /// <summary>");
        _ = source.AppendLine("    /// Metadata about a generated kernel.");
        _ = source.AppendLine("    /// </summary>");
        _ = source.AppendLine("    public sealed class KernelMetadata");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        public string Name { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string FullyQualifiedName { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string ContainingType { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string Namespace { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string[] Backends { get; init; } = Array.Empty<string>();");
        _ = source.AppendLine("        public int VectorSize { get; init; }");
        _ = source.AppendLine("        public bool IsParallel { get; init; }");
        _ = source.AppendLine("        public int ParameterCount { get; init; }");
        _ = source.AppendLine("    }");
        _ = source.AppendLine("}");

        return source.ToString();
    }
}
