// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Text;
using DotCompute.Generators.Models.Kernel;

namespace DotCompute.Generators.Kernel.Generation;

/// <summary>
/// Generates kernel registry code for runtime discovery.
/// </summary>
/// <remarks>
/// The generated <c>DotCompute.Generated.KernelRegistry</c> is the bridge the runtime's
/// <c>GeneratedKernelDiscoveryService</c> reflects over. In addition to descriptive metadata
/// it now carries the data required for actual execution:
/// <list type="bullet">
///   <item><description><c>CudaSource</c> / <c>CudaEntryPoint</c>: real <c>extern "C" __global__</c> CUDA-C.</description></item>
///   <item><description><c>Dimensions</c>: 1/2/3 detected from KernelContext intrinsic usage.</description></item>
///   <item><description><c>CpuInvoker</c>: an <c>Action&lt;object[], int, int&gt;</c> that runs the body over a flat work range.</description></item>
///   <item><description><c>Parameters</c>: ordered buffer/scalar descriptors.</description></item>
/// </list>
/// The registry is intentionally self-contained (it references no DotCompute.Runtime types)
/// because it is emitted into the user's assembly, which is not guaranteed to reference the runtime.
/// </remarks>
public sealed class KernelRegistrationEmitter
{
    /// <summary>
    /// Generates the kernel registry containing all kernel metadata.
    /// </summary>
    /// <param name="kernelMethods">The kernel methods to include in the registry.</param>
    /// <param name="kernelClasses">The kernel classes to include in the registry.</param>
    /// <returns>The generated registry source code.</returns>
    /// <remarks>
    /// The registry provides runtime access to all kernels via:
    /// - AddKernel: Registers kernel metadata
    /// - GetAvailableKernels: Returns list of all registered kernel names
    /// - GetKernelInfo: Retrieves metadata for a specific kernel
    /// - GetAllKernels: Returns the full metadata list (consumed by GeneratedKernelDiscoveryService)
    /// </remarks>
    public static string GenerateKernelRegistry(IReadOnlyList<KernelMethodInfo> kernelMethods, IReadOnlyList<KernelClassInfo> kernelClasses)
    {
        var source = new StringBuilder();
        _ = source.AppendLine("// <auto-generated/>");
        _ = source.AppendLine("#nullable enable");
        _ = source.AppendLine("#pragma warning disable // generated code");
        _ = source.AppendLine("using System;");
        _ = source.AppendLine("using System.Collections.Generic;");
        _ = source.AppendLine("using System.Linq;");
        _ = source.AppendLine();

        _ = source.AppendLine("namespace DotCompute.Generated");
        _ = source.AppendLine("{");
        _ = source.AppendLine("    /// <summary>");
        _ = source.AppendLine("    /// Registry of all generated kernels for runtime discovery.");
        _ = source.AppendLine("    /// </summary>");
        _ = source.AppendLine("    public static class KernelRegistry");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        private static readonly Dictionary<string, KernelMetadata> _kernels = new()");
        _ = source.AppendLine("        {");

        // The CPU invoker classes are accumulated and emitted after the registry class so they
        // can be referenced (forward reference) by the dictionary initializer above.
        var invokerClasses = new StringBuilder();

        foreach (var method in kernelMethods)
        {
            var fullName = $"{method.ContainingType}.{method.Name}";
            var dimensions = KernelExecutionMetadataEmitter.DetectDimensions(method);
            var (cudaSource, cudaEntryPoint) = KernelExecutionMetadataEmitter.GenerateCuda(method);
            var invokerClassName = KernelExecutionMetadataEmitter.GetInvokerClassName(method);

            _ = source.AppendLine($"            {{ \"{fullName}\", new KernelMetadata");
            _ = source.AppendLine("            {");
            _ = source.AppendLine($"                Name = \"{method.Name}\",");
            _ = source.AppendLine($"                FullyQualifiedName = \"{fullName}\",");
            _ = source.AppendLine($"                ContainingType = \"{method.ContainingType}\",");
            _ = source.AppendLine($"                Namespace = \"{method.Namespace}\",");
            _ = source.AppendLine($"                Backends = new[] {{ {string.Join(", ", method.Backends.Select(b => $"\"{b}\""))} }},");
            _ = source.AppendLine($"                VectorSize = {method.VectorSize},");
            _ = source.AppendLine($"                IsParallel = {(method.IsParallel ? "true" : "false")},");
            _ = source.AppendLine($"                ParameterCount = {method.Parameters.Count},");
            _ = source.AppendLine($"                Dimensions = {dimensions},");
            _ = source.AppendLine($"                CudaSource = {FormatCudaSource(cudaSource)},");
            _ = source.AppendLine($"                CudaEntryPoint = {FormatNullableString(cudaEntryPoint)},");
            _ = source.AppendLine($"                CpuInvoker = (System.Action<object[], int, int>){invokerClassName}.Invoke,");
            _ = source.AppendLine("                Parameters = new KernelParam[]");
            _ = source.AppendLine("                {");
            foreach (var param in method.Parameters)
            {
                var elementType = KernelExecutionMetadataEmitter.GetElementTypeName(param);
                var isReadOnly = KernelExecutionMetadataEmitter.GetIsReadOnly(param);
                _ = source.AppendLine(
                    $"                    new KernelParam {{ Name = \"{param.Name}\", IsBuffer = {Bool(param.IsBuffer)}, IsReadOnly = {Bool(isReadOnly)}, ElementType = \"{elementType}\" }},");
            }
            _ = source.AppendLine("                }");
            _ = source.AppendLine("            }},");

            // Build the matching CPU invoker class (always emitted so the delegate above resolves).
            string invokerSource;
            try
            {
                invokerSource = KernelExecutionMetadataEmitter.GenerateCpuInvokerClass(method, dimensions, invokerClassName);
            }
#pragma warning disable CA1031 // Do not catch general exception types - generator must never crash the build
            catch (Exception ex)
#pragma warning restore CA1031
            {
                invokerSource = BuildStubInvoker(invokerClassName, method.Name, ex.Message);
            }

            _ = invokerClasses.AppendLine(invokerSource);
        }

        _ = source.AppendLine("        };");
        _ = source.AppendLine();

        // Generate AddKernel method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Adds a kernel to the registry.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static void AddKernel(string name, KernelMetadata metadata)");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            _kernels[name] = metadata;");
        _ = source.AppendLine("        }");
        _ = source.AppendLine();

        // Generate GetAvailableKernels method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Gets a list of all available kernel names.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static IReadOnlyList<string> GetAvailableKernels()");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            return _kernels.Keys.ToList();");
        _ = source.AppendLine("        }");
        _ = source.AppendLine();

        // Generate GetKernelInfo method
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Gets metadata for a specific kernel.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static KernelMetadata? GetKernelInfo(string name)");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            return _kernels.TryGetValue(name, out var metadata) ? metadata : null;");
        _ = source.AppendLine("        }");
        _ = source.AppendLine();

        // Generate GetAllKernels method (consumed by the runtime discovery service)
        _ = source.AppendLine("        /// <summary>");
        _ = source.AppendLine("        /// Gets the metadata for every registered kernel.");
        _ = source.AppendLine("        /// </summary>");
        _ = source.AppendLine("        public static IReadOnlyList<KernelMetadata> GetAllKernels()");
        _ = source.AppendLine("        {");
        _ = source.AppendLine("            return _kernels.Values.ToList();");
        _ = source.AppendLine("        }");
        _ = source.AppendLine("    }");
        _ = source.AppendLine();

        // Generate KernelMetadata class
        _ = source.AppendLine("    /// <summary>");
        _ = source.AppendLine("    /// Metadata about a generated kernel.");
        _ = source.AppendLine("    /// </summary>");
        _ = source.AppendLine("    public sealed class KernelMetadata");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        public string Name { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string FullyQualifiedName { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string ContainingType { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string Namespace { get; init; } = string.Empty;");
        _ = source.AppendLine("        public string[] Backends { get; init; } = Array.Empty<string>();");
        _ = source.AppendLine("        public int VectorSize { get; init; }");
        _ = source.AppendLine("        public bool IsParallel { get; init; }");
        _ = source.AppendLine("        public int ParameterCount { get; init; }");
        _ = source.AppendLine("        public int Dimensions { get; init; }");
        _ = source.AppendLine("        public string? CudaSource { get; init; }");
        _ = source.AppendLine("        public string? CudaEntryPoint { get; init; }");
        _ = source.AppendLine("        public System.Delegate? CpuInvoker { get; init; }");
        _ = source.AppendLine("        public KernelParam[] Parameters { get; init; } = Array.Empty<KernelParam>();");
        _ = source.AppendLine("    }");
        _ = source.AppendLine();

        // Generate KernelParam class
        _ = source.AppendLine("    /// <summary>");
        _ = source.AppendLine("    /// Describes a single kernel parameter (buffer or scalar).");
        _ = source.AppendLine("    /// </summary>");
        _ = source.AppendLine("    public sealed class KernelParam");
        _ = source.AppendLine("    {");
        _ = source.AppendLine("        public string Name { get; init; } = string.Empty;");
        _ = source.AppendLine("        public bool IsBuffer { get; init; }");
        _ = source.AppendLine("        public bool IsReadOnly { get; init; }");
        _ = source.AppendLine("        public string ElementType { get; init; } = string.Empty;");
        _ = source.AppendLine("    }");
        _ = source.AppendLine();

        // Emit the CPU invoker classes (referenced by the registry above).
        _ = source.Append(invokerClasses);

        _ = source.AppendLine("}");

        return source.ToString();
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string FormatNullableString(string? value)
        => value is null ? "null" : $"\"{value}\"";

    private static string FormatCudaSource(string? cudaSource)
    {
        if (cudaSource is null)
        {
            return "null";
        }

        // Verbatim string literal: escape embedded double-quotes (extern "C") by doubling them.
        return "@\"" + cudaSource.Replace("\"", "\"\"") + "\"";
    }

    private static string BuildStubInvoker(string invokerClassName, string methodName, string reason)
    {
        var builder = new StringBuilder();
        _ = builder.AppendLine($"    public static class {invokerClassName}");
        _ = builder.AppendLine("    {");
        _ = builder.AppendLine("        public static void Invoke(object[] args, int start, int end)");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine($"            throw new System.NotSupportedException(\"CPU invoker generation failed for {methodName}: {reason.Replace("\"", "'")}\");");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine("    }");
        return builder.ToString();
    }
}
