// Copyright (c) 2025 Michael Ivertowski
// Licensed under the MIT License. See LICENSE file in the project root for license information.

namespace DotCompute.Core.System;

/// <summary>
/// Comprehensive system information snapshot.
/// </summary>
/// <remarks>
/// <para>
/// Provides a complete view of system resources including platform details, CPU information,
/// memory statistics, process metrics, and disk space. All properties are init-only for
/// immutability after construction.
/// </para>
/// <para>
/// Generated by SystemInfoManager with platform-specific data collection for Windows (WMI),
/// Linux (/proc), macOS (sysctl/vm_stat), and FreeBSD.
/// </para>
/// <para><b>Thread Safety</b>: Immutable snapshot, safe for concurrent access.</para>
/// </remarks>
public sealed class SystemInfo
{
    // Platform Information

    /// <summary>
    /// Gets or sets the operating system platform type.
    /// </summary>
    /// <remarks>
    /// Identifies the underlying OS (Windows, Linux, macOS, FreeBSD) to determine
    /// which platform-specific APIs were used for data collection.
    /// </remarks>
    public PlatformType Platform { get; init; }

    /// <summary>
    /// Gets or sets the system architecture (e.g., X64, Arm64).
    /// </summary>
    /// <remarks>
    /// CPU architecture from RuntimeInformation.OSArchitecture.
    /// Common values: X64, Arm64, X86, Arm.
    /// </remarks>
    public string Architecture { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the operating system description.
    /// </summary>
    /// <remarks>
    /// Friendly OS description including version information (e.g., "Microsoft Windows 11",
    /// "Ubuntu 22.04", "macOS 14 Sonoma"). From RuntimeInformation.OSDescription.
    /// </remarks>
    public string OSDescription { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the .NET runtime framework description.
    /// </summary>
    /// <remarks>
    /// Complete .NET runtime version string (e.g., ".NET 9.0.0"). From
    /// RuntimeInformation.FrameworkDescription.
    /// </remarks>
    public string FrameworkDescription { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the number of logical processors.
    /// </summary>
    /// <remarks>
    /// Total logical CPU count including hyper-threading. From <see cref="Environment.ProcessorCount"/>.
    /// </remarks>
    public int ProcessorCount { get; init; }

    /// <summary>
    /// Gets or sets the machine name/hostname.
    /// </summary>
    /// <remarks>
    /// Computer name from <see cref="Environment.MachineName"/>. Used for distributed system identification.
    /// </remarks>
    public string MachineName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets whether the operating system is 64-bit.
    /// </summary>
    /// <remarks>
    /// True for 64-bit operating systems. From <see cref="Environment.Is64BitOperatingSystem"/>.
    /// </remarks>
    public bool Is64BitOS { get; init; }

    /// <summary>
    /// Gets or sets whether the current process is 64-bit.
    /// </summary>
    /// <remarks>
    /// True for 64-bit processes. From <see cref="Environment.Is64BitProcess"/>. Can be false
    /// on 64-bit OS if running as 32-bit process (WOW64).
    /// </remarks>
    public bool Is64BitProcess { get; init; }

    // Memory Information

    /// <summary>
    /// Gets or sets the total physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// Total RAM installed on the system. Collected via platform-specific APIs:
    /// Windows (GlobalMemoryStatusEx), Linux (/proc/meminfo), macOS (sysctl hw.memsize).
    /// </remarks>
    public long TotalPhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the available physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// Free RAM available for allocation. Does not include cached/buffered memory
    /// that could be reclaimed on Linux/macOS.
    /// </remarks>
    public long AvailablePhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the used physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// Calculated as TotalPhysicalMemory - AvailablePhysicalMemory. Includes
    /// active process memory, caches, and buffers.
    /// </remarks>
    public long UsedPhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the physical memory usage percentage (0.0-100.0).
    /// </summary>
    /// <remarks>
    /// Percentage of total physical memory in use. Values above 90% may indicate
    /// memory pressure requiring optimization or additional RAM.
    /// </remarks>
    public double MemoryUsagePercentage { get; init; }

    /// <summary>
    /// Gets or sets the total virtual memory in bytes.
    /// </summary>
    /// <remarks>
    /// Total virtual address space available (physical RAM + page file/swap).
    /// Significantly larger on 64-bit systems.
    /// </remarks>
    public long TotalVirtualMemory { get; init; }

    /// <summary>
    /// Gets or sets the available virtual memory in bytes.
    /// </summary>
    /// <remarks>
    /// Free virtual memory available for allocation. Includes both physical RAM
    /// and swap space.
    /// </remarks>
    public long AvailableVirtualMemory { get; init; }

    // CPU Information

    /// <summary>
    /// Gets or sets the CPU model name.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Detailed CPU model string from vendor (e.g., "Intel(R) Core(TM) i9-13900K",
    /// "AMD Ryzen 9 7950X", "Apple M2 Pro"). Platform-specific sources:
    /// </para>
    /// <list type="bullet">
    /// <item>Windows: WMI Win32_Processor Name property</item>
    /// <item>Linux: /proc/cpuinfo "model name" field</item>
    /// <item>macOS: sysctl machdep.cpu.brand_string</item>
    /// </list>
    /// </remarks>
    public string CpuName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CPU frequency in MHz.
    /// </summary>
    /// <remarks>
    /// Base clock frequency. May differ from current/boost frequency under load.
    /// Retrieved from platform-specific CPU information.
    /// </remarks>
    public int CpuFrequencyMHz { get; init; }

    /// <summary>
    /// Gets or sets the number of physical CPU cores.
    /// </summary>
    /// <remarks>
    /// Physical core count excluding hyper-threading. Typically half of ProcessorCount
    /// on Intel CPUs with hyper-threading enabled.
    /// </remarks>
    public int CpuCores { get; init; }

    /// <summary>
    /// Gets or sets the number of logical CPU threads.
    /// </summary>
    /// <remarks>
    /// Total logical processors including hyper-threading/SMT. Usually equals ProcessorCount.
    /// </remarks>
    public int CpuThreads { get; init; }

    /// <summary>
    /// Gets or sets the CPU usage percentage (0.0-100.0).
    /// </summary>
    /// <remarks>
    /// System-wide CPU utilization at snapshot time. Averaged across all cores.
    /// Values near 100% indicate CPU saturation.
    /// </remarks>
    public double CpuUsagePercentage { get; init; }

    /// <summary>
    /// Gets or sets the CPU architecture string.
    /// </summary>
    /// <remarks>
    /// Detailed architecture information (e.g., "x86_64", "aarch64"). May include
    /// microarchitecture details on some platforms.
    /// </remarks>
    public string CpuArchitecture { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CPU features/instruction sets.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Comma-separated list of supported CPU features and instruction set extensions.
    /// Important for SIMD optimization and hardware acceleration.
    /// </para>
    /// <para><b>Examples</b>: "AVX2, FMA, AVX-512", "NEON, CRC32", "SSE4.2, POPCNT"</para>
    /// </remarks>
    public string CpuFeatures { get; init; } = string.Empty;

    // Process Information

    /// <summary>
    /// Gets or sets the current process memory usage in bytes.
    /// </summary>
    /// <remarks>
    /// Working set size (physical memory used by current process). From
    /// Process.WorkingSet64. Includes both managed and native memory.
    /// </remarks>
    public long ProcessMemory { get; init; }

    /// <summary>
    /// Gets or sets the current process virtual memory usage in bytes.
    /// </summary>
    /// <remarks>
    /// Total virtual address space reserved by process. From Process.VirtualMemorySize64.
    /// Typically much larger than ProcessMemory on 64-bit systems.
    /// </remarks>
    public long ProcessVirtualMemory { get; init; }

    /// <summary>
    /// Gets or sets the current process thread count.
    /// </summary>
    /// <remarks>
    /// Number of threads in current process. From Process.Threads. Includes
    /// thread pool workers, GC threads, and application threads.
    /// </remarks>
    public int ProcessThreadCount { get; init; }

    /// <summary>
    /// Gets or sets the current process handle count.
    /// </summary>
    /// <remarks>
    /// Number of open handles (files, sockets, synchronization objects, etc.). From
    /// Process.HandleCount. Windows-specific metric.
    /// </remarks>
    public int ProcessHandleCount { get; init; }

    /// <summary>
    /// Gets or sets the current process uptime.
    /// </summary>
    /// <remarks>
    /// Duration since process started. Calculated from Process.StartTime.
    /// </remarks>
    public TimeSpan ProcessUptime { get; init; }

    // Disk Information

    /// <summary>
    /// Gets or sets the total disk space in bytes for the current drive.
    /// </summary>
    /// <remarks>
    /// Total capacity of drive containing current directory. From <see cref="DriveInfo.TotalSize"/>.
    /// </remarks>
    public long DiskSpaceTotal { get; init; }

    /// <summary>
    /// Gets or sets the available disk space in bytes.
    /// </summary>
    /// <remarks>
    /// Free space available to current user. From <see cref="DriveInfo.AvailableFreeSpace"/>.
    /// May differ from TotalFreeSpace due to disk quotas.
    /// </remarks>
    public long DiskSpaceAvailable { get; init; }

    /// <summary>
    /// Gets or sets the used disk space in bytes.
    /// </summary>
    /// <remarks>
    /// Calculated as DiskSpaceTotal - DiskSpaceAvailable. Space consumed by files
    /// and filesystem metadata.
    /// </remarks>
    public long DiskSpaceUsed { get; init; }

    // Metadata

    /// <summary>
    /// Gets or sets the timestamp when this snapshot was captured.
    /// </summary>
    /// <remarks>
    /// UTC timestamp indicating when system information was collected. Used for
    /// monitoring trends and detecting stale snapshots.
    /// </remarks>
    public DateTimeOffset Timestamp { get; init; }
}

/// <summary>
/// Detailed system memory information with GC statistics.
/// </summary>
/// <remarks>
/// <para>
/// Extended memory metrics including physical/virtual memory breakdown and .NET
/// garbage collection statistics. Useful for memory pressure analysis and
/// performance diagnostics.
/// </para>
/// <para>
/// Retrieved by SystemInfoManager.GetDetailedMemoryInfo.
/// </para>
/// <para><b>Thread Safety</b>: Immutable snapshot, safe for concurrent access.</para>
/// </remarks>
public sealed class SystemMemoryInfo
{
    /// <summary>
    /// Gets or sets the total physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// Total RAM installed on system. Same as <see cref="SystemInfo.TotalPhysicalMemory"/>.
    /// </remarks>
    public long TotalPhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the available physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// Free RAM available for immediate allocation without swapping.
    /// </remarks>
    public long AvailablePhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the used physical memory in bytes.
    /// </summary>
    /// <remarks>
    /// RAM currently in use by all processes, caches, and buffers.
    /// </remarks>
    public long UsedPhysicalMemory { get; init; }

    /// <summary>
    /// Gets or sets the physical memory usage percentage (0.0-100.0).
    /// </summary>
    /// <remarks>
    /// Percentage of RAM in use. Values &gt; 90% indicate memory pressure.
    /// Consider increasing RAM or optimizing memory usage.
    /// </remarks>
    public double PhysicalMemoryUsagePercentage { get; init; }

    /// <summary>
    /// Gets or sets the total virtual memory in bytes.
    /// </summary>
    /// <remarks>
    /// Total virtual address space (RAM + page file/swap). Much larger on 64-bit systems.
    /// </remarks>
    public long TotalVirtualMemory { get; init; }

    /// <summary>
    /// Gets or sets the available virtual memory in bytes.
    /// </summary>
    /// <remarks>
    /// Free virtual memory including swap space. Running out indicates severe memory pressure.
    /// </remarks>
    public long AvailableVirtualMemory { get; init; }

    /// <summary>
    /// Gets or sets the current process memory usage in bytes.
    /// </summary>
    /// <remarks>
    /// Working set size of current process. Includes all managed and native allocations.
    /// </remarks>
    public long ProcessMemoryUsage { get; init; }

    /// <summary>
    /// Gets or sets the current process virtual memory usage in bytes.
    /// </summary>
    /// <remarks>
    /// Total virtual address space reserved by current process.
    /// </remarks>
    public long ProcessVirtualMemoryUsage { get; init; }

    /// <summary>
    /// Gets or sets the total memory allocated by the .NET Garbage Collector.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Managed heap size from <see cref="GC.GetTotalMemory"/>. Does not include
    /// native allocations or unmanaged memory.
    /// </para>
    /// <para>
    /// Large values may indicate memory leaks, excessive allocations, or LOH
    /// fragmentation in managed code.
    /// </para>
    /// </remarks>
    public long GCTotalMemory { get; init; }

    /// <summary>
    /// Gets or sets the number of Generation 0 garbage collections.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Gen0 collections are fast and collect short-lived objects. From
    /// <see cref="GC.CollectionCount"/>. High frequency is normal and expected.
    /// </para>
    /// <para><b>Typical Range</b>: Thousands to millions during application lifetime.</para>
    /// </remarks>
    public int GCGen0Collections { get; init; }

    /// <summary>
    /// Gets or sets the number of Generation 1 garbage collections.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Gen1 collections are medium-duration and collect medium-lived objects. From
    /// <see cref="GC.CollectionCount"/>. Usually 10-20% of Gen0 collection count.
    /// </para>
    /// <para><b>Typical Range</b>: Hundreds to tens of thousands.</para>
    /// </remarks>
    public int GCGen1Collections { get; init; }

    /// <summary>
    /// Gets or sets the number of Generation 2 garbage collections.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Gen2 collections are expensive full-heap collections. From
    /// <see cref="GC.CollectionCount"/>. High frequency indicates memory pressure
    /// or excessive long-lived objects.
    /// </para>
    /// <para><b>Performance Impact</b>: Each Gen2 collection can pause application 10-100ms+.</para>
    /// <para><b>Optimization</b>: Reduce to &lt; 1 per second for optimal performance.</para>
    /// </remarks>
    public int GCGen2Collections { get; init; }

    /// <summary>
    /// Gets or sets the timestamp when this information was collected.
    /// </summary>
    /// <remarks>
    /// UTC timestamp of memory snapshot capture. Useful for tracking memory trends
    /// over time and correlating with application events.
    /// </remarks>
    public DateTimeOffset Timestamp { get; init; }
}
